version: "3.8"

services:
  php:
    container_name: symfony-test
    hostname: symfony-test
    networks:
      - caddy-network
    build: .
    environment:
      - SYMFONY_PARAMS=${SYMFONY_PARAMS}
    ports:
      - "8080:8000"
    volumes:
      - ./app:/var/www/html

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db-data:

networks:
  caddy-network:
    external: true
    name: caddy-network
