version: "3.8"

services:
  php-apache:
    build:
      context: ./docker
    environment:
      - SYMFONY_PARAMS=${SYMFONY_PARAMS}
    volumes:
      - ./app/:/var/www/html
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.6.4-focal
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      TZ: "Europe/Paris"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"

volumes:
  dbdata:
