version: "3.8"

services:
  php8-sf6:
    container_name: php8-sf6
    build:
      context: ./docker
    environment:
      - SYMFONY_PARAMS=${SYMFONY_PARAMS}
    ports:
      - "8080:8000"
    volumes:
      - ./app:/var/www/html

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db-data:
